### ISSUE TITLE
关于插件

### ISSUE THREAD

**Issue by QQzhuqiu** [s52047qwas/nonebot_plugin_xiuxian#1]
这个和youzai的修仙插件好像啊，这个以后会返回图片吗

**Comment by s52047qwas** [comment]
部分功能参考yunzai，图片功能暂时还没空做，目前是先把基础功能都实现先

**Comment by s52047qwas** [comment]
> 部分功能参考yunzai，图片功能暂时还没空做，目前是先把基础功能都实现先

部分功能参考yunzai，图片功能暂时还没空做，目前是先把基础功能都实现先

**Comment by s52047qwas** [comment]
> 这个和youzai的修仙插件好像啊，这个以后会返回图片吗

部分功能参考yunzai，图片功能暂时还没空做，目前是先把基础功能都实现先
