### ISSUE TITLE
报错：'Xiuconfig' object has no attribute 'sql_buff'

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#103]
git clone 过一次，换回pip版本就出现这个报错了
![image](https://user-images.githubusercontent.com/70925546/200980739-36fcc414-117e-456a-83d2-066702a26733.png)

**Comment by Z735803792** [comment]
那请问一般多久更新一次pypi呢，我看应该更新了很多东西想试试，有没有git clone的方法？
我用git clone到plugin文件似乎没办法加载所有文件（悲）
![image](https://user-images.githubusercontent.com/70925546/200997166-d5642a19-81d4-443b-9721-9a2fd57c78aa.png)

**Comment by Shinoakii** [comment]
当为放置为plugins目录使用时，请修改__init__.py 文件的42行：src=''的内容，一般情况下是 src='src.plugins.'

**Comment by Z735803792** [comment]
1、用指令`我的背包`报错
![image](https://user-images.githubusercontent.com/70925546/201008719-64aab40a-bccf-465c-98ec-13930dd6c50d.png)
2、`访市查看`一直显示是空空如也

**Comment by Z735803792** [comment]
是哪一个，我把左边列的删除了并没有用
![image](https://user-images.githubusercontent.com/70925546/201238514-d5ec57b0-8809-4bc5-affa-b330644dc788.png)

**Comment by Shinoakii** [comment]
不是这一张表，是back表

**Comment by Z735803792** [comment]
是这个大气血丹吗，还是包括上面都是
![image](https://user-images.githubusercontent.com/70925546/201275896-01707ad2-9369-472f-b282-4fe165f74884.png)

**Comment by Shinoakii** [comment]
上面的都是，goods_id为1、2、3的都要删掉
