### ISSUE TITLE
【bug】拍卖行无法结算等

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#109]
已确保其他iss没有提这个问题
### 1、如图
![image](https://user-images.githubusercontent.com/70925546/201499081-350ab821-3d0e-40a4-a2ea-5f1d13a453b8.png)
![image](https://user-images.githubusercontent.com/70925546/201499276-f9f66d69-8518-4615-952a-b8796a21a271.png)
### 2、秘境无法刷新
一个50次的秘境，如果没有摸完50次，两天了也没有刷新

另外访市是不是只能交易？有没有那种常驻卖出的商品？访市交易可以跨群吗

**Comment by Shinoakii** [comment]
1、更新了拍卖会日志，再次卡住请贴下日志
2、50次是被人修改后的次数，去rift文件夹下的config.json文件把秘境的count字段减小点，目前没关闭指令，重启bot可以刷新
3、坊市有超管可以上架物品的指令，具体看背包帮助
4、不可以跨群
