### ISSUE TITLE
[bug]修为超额

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [s52047qwas/nonebot_plugin_xiuxian#112]
首先修为不会超过当前突破值的1.5倍。
在上个版本里，捆仙绳任务给的修为很高，一段时间观察后，第一名居然修为比第二名超出了3倍多，金仙中修为为169242599，明显超出几倍，因为宗门任务的额外修为不触发上限机制，导致了这种奇怪的bug。
建议在宗门任务，秘境等其他可以获取修为的事件，最后都加个最高修为判断

**Comment by Z735803792** [comment]
有报错了，他灵石出关显示这个
![image](https://user-images.githubusercontent.com/70925546/202979015-faf87ec7-84b4-462c-9459-ec617a929535.png)

**Comment by Z735803792** [comment]
由于宗门任务金银阁修为太多，在不破坏公平的情况下第一名任然比第二名高出1.5倍下面是排行榜
```
 位面境界排行榜TOP10
第1位 无始大帝 太乙境中期,修为451408077
第2位 蓬莱山泥若 太乙境中期,修为174458157.5
第3位 段德道人 太乙境初期,修为168019728.5
第4位 遗忘古迹 金仙境圆满,修为138658536
第5位 晚安 金仙境中期,修为120236038
第6位 混沌魔尊 慈航 金仙境中期,修为82884968.5
```
查了下对应的data文件里面的修为
```
金仙境圆满：80968000
太乙境初期：120968000
太乙境中期：140968000
太乙境圆满：160968000
```
我认为默认的修为不超过突破值的1.5倍限制，没有发挥作用，是很大的问题。
**建议可以在宗门任务的修为获取里面加上这个判断**
