### ISSUE TITLE
[bug]websocket call api send_msg timeout

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#115]
如图，在启动nb端的时候就会报错，目前暂未发现重大影响，就是有时候会突然卡主然后这样报错
![image](https://user-images.githubusercontent.com/70925546/202660561-babc4220-ee76-42e6-83ef-8447ad09490d.png)

**Comment by Shinoakii** [comment]
你网卡了.jpg
