### ISSUE TITLE
是否可以加个设置变更，图片模式和文字模式

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#118]
### 图片形式→图片or文字
虽然明白封杀问题严重，但我群认为文字模式才是这个小游戏的魅力，变成图片后互动性低了很多。
希望可以把旧版本的原文字输出也保留，改成默认图片形式，可以手动加config里改成文字输出

**Comment by Shinoakii** [comment]
![image](https://user-images.githubusercontent.com/86348789/203460886-28eac8af-c9b4-438a-912a-372cffe2b9b6.png)
