### ISSUE TITLE
宗门踢人的时候清空的是自己的贡献

### ISSUE THREAD

**Issue by Sam5440** [s52047qwas/nonebot_plugin_xiuxian#133]

**Comment by Sam5440** [comment]
![image](https://user-images.githubusercontent.com/47051833/216541051-6f140d80-1ab5-4e62-a541-a5537e59db1a.png)

**Comment by Sam5440** [comment]
![image](https://user-images.githubusercontent.com/47051833/216543867-fbe96df5-4800-48df-b468-2935633b95a3.png)

**Comment by Shinoakii** [comment]
done
