### ISSUE TITLE
更新后突破报错

### ISSUE THREAD

**Issue by wangyousama** [s52047qwas/nonebot_plugin_xiuxian#17]
![image](https://user-images.githubusercontent.com/107395159/189009496-abcd60c8-afe3-4e0e-b9af-d0f202d2e1e8.png)
没有修改任何东西，修为够不够都是报错这个，其他报错也挺多的，

**Comment by wuyukwi** [comment]
我已经改好了，等分支合并过去就可以了

**Comment by s52047qwas** [comment]
已合并
