### ISSUE TITLE
【报错】无法安装

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#2]
python3.9.13，nonebot2=2.0.0b5
如题，下面是安装报错
```
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting nonebot_plugin_xiuxian
  Using cached https://mirrors.aliyun.com/pypi/packages/bb/3f/2f3372ff9382f85acd25ab1fb0c79319ca39dadb905cb7c02919b305102a/nonebot_plugin_xiuxian-0.2.1.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://mirrors.aliyun.com/pypi/packages/f8/d6/0d22c9caf4fd57abdda5430ea249f06a7e493f1f39b759a59faf7a44c104/nonebot_plugin_xiuxian-0.2.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... done
  Using cached https://mirrors.aliyun.com/pypi/packages/99/18/1025bedd210b5cabd427d59202a12c8416e2e3d9c8bf66e056ba84b41956/nonebot_plugin_xiuxian-0.1.tar.gz (6.6 kB)
  Preparing metadata (setup.py) ... done
ERROR: Cannot install nonebot-plugin-xiuxian==0.1, nonebot-plugin-xiuxian==0.2 and nonebot-plugin-xiuxian==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    nonebot-plugin-xiuxian 0.2.1 depends on collections
    nonebot-plugin-xiuxian 0.2 depends on collections
    nonebot-plugin-xiuxian 0.1 depends on collections

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by s52047qwas** [comment]
> python3.9.13，nonebot2=2.0.0b5 如题，下面是安装报错
> 
> ```
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
> Collecting nonebot_plugin_xiuxian
>   Using cached https://mirrors.aliyun.com/pypi/packages/bb/3f/2f3372ff9382f85acd25ab1fb0c79319ca39dadb905cb7c02919b305102a/nonebot_plugin_xiuxian-0.2.1.tar.gz (7.4 kB)
>   Preparing metadata (setup.py) ... done
>   Using cached https://mirrors.aliyun.com/pypi/packages/f8/d6/0d22c9caf4fd57abdda5430ea249f06a7e493f1f39b759a59faf7a44c104/nonebot_plugin_xiuxian-0.2.tar.gz (7.4 kB)
>   Preparing metadata (setup.py) ... done
>   Using cached https://mirrors.aliyun.com/pypi/packages/99/18/1025bedd210b5cabd427d59202a12c8416e2e3d9c8bf66e056ba84b41956/nonebot_plugin_xiuxian-0.1.tar.gz (6.6 kB)
>   Preparing metadata (setup.py) ... done
> ERROR: Cannot install nonebot-plugin-xiuxian==0.1, nonebot-plugin-xiuxian==0.2 and nonebot-plugin-xiuxian==0.2.1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     nonebot-plugin-xiuxian 0.2.1 depends on collections
>     nonebot-plugin-xiuxian 0.2 depends on collections
>     nonebot-plugin-xiuxian 0.1 depends on collections
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> ```
可以现在github处拉取代码至bot目录，plugin处，pip处问题在处理中，可能是缺少对应的whl文件导致的问题，我这边修复一下

**Comment by s52047qwas** [comment]
> 可以现在github处拉取代码至bot目录，plugin处，pip处问题在处理中，可能是缺少对应的whl文件导致的问题，我这边修复一下

已修复该问题
