### ISSUE TITLE
发送突破报错

### ISSUE THREAD

**Issue by linword** [s52047qwas/nonebot_plugin_xiuxian#28]
![image](https://user-images.githubusercontent.com/43131361/189116177-418fce39-48c8-496a-965b-2f87d91fe17b.png)
json文件我全部git pull后然后替换掉了`data/xiuxian/`目录下的文件，更新的版本是0.3.1

**Comment by s52047qwas** [comment]
sorry，因为昨天更新json于数据库文件的分离，目前在install处的包尚未更新，预计修复部分bug后才会更新install处的包

**Comment by linword** [comment]
哈哈哈嗝，没事没事，大佬辛苦
