### ISSUE TITLE
提个想法和目前发现的bug

### ISSUE THREAD

**Issue by linword** [s52047qwas/nonebot_plugin_xiuxian#3]
1.可以考虑加个探索嘛？然后探索有事件之类的？好的坏的都行。
2.灵石可赠送？
3.金银阁，发现一个bug，比如说押注200，然后让猜大小，不按提示的格式输入，比如“大200”，或者其他“小”or“大”+数字，好像结果都错的，出的骰子点数5，输的是“大200”，回应的是猜错了...不知道这算不算

**Comment by s52047qwas** [comment]
你好，根据你的问题：
1、探索功能，目前打算是完善丹药和装备内容后才加上去
2、赠送灵石可以增加，晚点加一下
3、金银阁目前只对金额做了校验，其他地方没有加，我修复下这个问题

**Comment by linword** [comment]
大佬辛苦
