### ISSUE TITLE
想问一下gm权限的使用命令可以方便演示一下吗，人笨不懂。。。

### ISSUE THREAD

**Issue by LSGLSH** [s52047qwas/nonebot_plugin_xiuxian#34]
我看了更新啥gm权限，确实是不知道怎么使用

**Comment by s52047qwas** [comment]
指令：神秘代码+灵石+艾特对应的人/或者他的道号，权限条件为为env处设置的SUPERUSERS
示例：神秘代码100@xxx

**Comment by LSGLSH** [comment]
> 指令：神秘代码+灵石+艾特对应的人/或者他的道号，权限条件为为env处设置的SUPERUSERS 示例：神秘代码100@xxx

恕我愚笨，神秘代码是命令吗

**Comment by LSGLSH** [comment]
> 指令：神秘代码+灵石+艾特对应的人/或者他的道号，权限条件为为env处设置的SUPERUSERS 示例：神秘代码100@xxx

![-6e9d28529cd7920e](https://user-images.githubusercontent.com/106002475/189820452-838a47b0-5d96-4656-a463-55e8be874f13.png)

**Comment by LSGLSH** [comment]
> 指令：神秘代码+灵石+艾特对应的人/或者他的道号，权限条件为为env处设置的SUPERUSERS 示例：神秘代码100@xxx

确实是没有反馈

**Comment by s52047qwas** [comment]
需要设置nonebot配置为超级管理员

**Comment by LSGLSH** [comment]
> 需要设置nonebot配置为超级管理员

已经设置我就是超级管理员了

**Comment by LSGLSH** [comment]
> 需要设置nonebot配置为超级管理员

确实是没有反馈

**Comment by s52047qwas** [comment]
请确认是否在env配置处设置超级管理员，非超级管理员不会反馈消息

**Comment by s52047qwas** [comment]
另外需确认版本是否更新为0.3.3

**Comment by LSGLSH** [comment]
> 另外需确认版本是否更新为0.3.3

确定自己是超级管理员，然后版本我是今天直接下载的github仓库里面的

**Comment by s52047qwas** [comment]
你加下群看下吧，760517008

**Comment by s52047qwas** [comment]
知道问题，指令是神秘力量，写错了
神秘力量100@xxx

**Comment by Z735803792** [comment]
不会用+1，
       神秘力量100@xx
没有回应也没加灵石（操作是自己艾特自己，自己是超管）

**Comment by s52047qwas** [comment]
> 不会用+1， 神秘力量100@xx 没有回应也没加灵石（操作是自己艾特自己，自己是超管）

有更新版本吗

**Comment by Z735803792** [comment]
更新了正常了，谢谢大佬
