### ISSUE TITLE
今天更新的偷灵石报错

### ISSUE THREAD

**Issue by wangyousama** [s52047qwas/nonebot_plugin_xiuxian#35]
重复偷一个人是不是有CD？重复偷就会报错，而不是返回CD消息

**Comment by s52047qwas** [comment]
内测阶段。。别用先。有些问题没有修复

**Comment by s52047qwas** [comment]
已经发布一版，似乎还存在些问题

**Comment by wangyousama** [comment]
> 已经发布了一版，似乎还存在一些问题

已经更新，有问题会把报错发上来

**Comment by s52047qwas** [comment]
好的，感谢你的支持

**Comment by wangyousama** [comment]
![}`LIY O UEJRCM (0M}MSN](https://user-images.githubusercontent.com/107395159/190176205-cf7bb4a7-3ecf-4a6b-9e37-3d4032078a04.png)
![~QXS7OIO201IYUJ9SPUAF_H](https://user-images.githubusercontent.com/107395159/190176221-a46ade78-304e-4b1d-9611-ec48abebbc71.png)
![8A ![Uploading ]}`LIY]O]UEJRCM](0M}MSN.png…]()
![Uploading ~QXS7OIO201IYUJ9SPUAF_H.png…]()
I27DYLPQ5D`3A@1G)W](https://user-images.githubusercontent.com/107395159/190176231-4c00ed06-7794-457e-aa99-5fe0f66726c9.png)
目前每次偷灵石就会弹这个报错，几率前几次还好，后面就全是失败了
环境是腾讯云windows sever 2012R2   部署在真寻BOT上的

**Comment by wangyousama** [comment]
不知道是我的问题还是插件的问题

**Comment by s52047qwas** [comment]
> 不知道是我的问题还是插件的问题

已修复，nonebot install预计明天提交修复

**Comment by Z735803792** [comment]
偷灵石玩法，玩多了，两个人都会少，不知道是不是错觉，偷失败是会被对面抢吗？

**Comment by s52047qwas** [comment]
> 偷灵石玩法，玩多了，两个人都会少，不知道是不是错觉，偷失败是会被对面抢吗？


因为偷失败的惩罚比较高，可以在XiuConfig.py处调整，当前为，成功偷取为5-100，失败惩罚70
