### ISSUE TITLE
插件响应问题（？

### ISSUE THREAD

**Issue by SEVEN-6174** [s52047qwas/nonebot_plugin_xiuxian#4]
装上插件之后
另一个ai模块没有触发
我猜测是由于程序时间限制的部分
ai的priority=998
而time_mes = on_message(priority=100)
所以在结束之前拦截了
但是理论上不会触发，因为会直接pass
我也搞不懂
而且删掉插件就正常
（最后改成time_mes = on_message(priority=999)完成）

**Comment by s52047qwas** [comment]
原因我这边也不清楚，该模块并没有block掉其他数据，我调整为999吧

**Comment by zyp981204** [comment]
![1662521512647_6706A7B9-C35D-4d80-AADA-593E5871269F](https://user-images.githubusercontent.com/52909621/188782710-d71945cf-cbb4-4322-b291-127c257d0ce8.png)
请问这个发送消息没响应，和这个是一个问题么，应该怎么样处理？
