### ISSUE TITLE
闭关修炼能否根据灵根品质和境界来加速获取修为呢？

### ISSUE THREAD

**Issue by wangyousama** [s52047qwas/nonebot_plugin_xiuxian#5]
一分钟十点太慢了，到后面挂很久估计都不能突破一次，等后面装备系统做出来也可以加点增加修炼速度的装备？

**Comment by s52047qwas** [comment]
后面会根据灵根，境界，装备，丹药增加修炼速度，目前因为开发时间较少，所以进度比较慢一点

**Comment by wangyousama** [comment]
> 后面会根据灵根，境界，装备，丹药增加修炼速度，目前因为只有周末才有空开发下，所以进度比较慢

会不会开发对战功能呢？根据技能的发动几率和装备技能的发动几率来对战？

**Comment by s52047qwas** [comment]
> > 后面会根据灵根，境界，装备，丹药增加修炼速度，目前因为只有周末才有空开发下，所以进度比较慢
> 
> 会不会开发对战功能呢？根据技能的发动几率和装备技能的发动几率来对战？

战斗系统还在思考如何实现，to do状态

**Comment by wangyousama** [comment]
> > > 后面会根据灵根，境界，装备，丹药增加修炼速度，目前因为只有周末才有空开发下，所以进度比较慢
> > 
> > 
> > 会不会开发对战功能呢？根据技能的发动几率和装备技能的发动几率来对战？
> 
> 战斗系统还在思考如何实现，to do状态

恩恩 谢谢大佬
