### ISSUE TITLE
排行榜的触发问题

### ISSUE THREAD

**Issue by LoCCai** [s52047qwas/nonebot_plugin_xiuxian#50]
用命令触发排行榜时，如果不添加空的命令符，无法触发排行，建议改为正则触发器，然后使用关键词处理

@command.rank.handle()
async def _(event: GroupMessageEvent):
    """排行榜"""
    message = str(event.message)
    if ('排行榜' in message) and (('修仙' in message) or ('境界' in message)):
        p_rank = sql_message.realm_top()
        await rank.finish(message=p_rank)
    elif ('排行榜' in message) and (('灵石' in message) or ('财力' in message)):
        a_rank = sql_message.stone_top()
        await rank.finish(message=a_rank)
    elif ('排行榜' in message) and (('战斗' in message) or ('战力' in message)):
        a_rank = sql_message.power_top()
        await rank.finish(message=a_rank)
    elif ('排行榜' in message) and (('宗门' in message) or ('宗门建设度' in message)):
        s_rank, _ = sql_message.scale_top()
        await rank.finish(message=s_rank)

**Comment by s52047qwas** [comment]
已更新
