### ISSUE TITLE
[bug] NoneBot v2.0.0rc1下无法运行

### ISSUE THREAD

**Issue by bywhite0** [s52047qwas/nonebot_plugin_xiuxian#53]
nonebot/nonebot2#1160

最新版 NoneBot 移除了`State`注入函数，故使用最新版无法运行。

https://github.com/s52047qwas/nonebot_plugin_xiuxian/blob/2648dd2f8a55639cf57f9fb3d7e321bbba936483/nonebot_plugin_xiuxian/__init__.py#L18

**Comment by Shinoakii** [comment]
已修复
