### ISSUE TITLE
一些想法

### ISSUE THREAD

**Issue by Darphas** [s52047qwas/nonebot_plugin_xiuxian#64]
增加职业系统：比如剑修符修器修丹修等等，还可以有修仙修魔等对立职业
探索系统：可以去各种地方探索，获得各种素材，可添加随机事件
功德系统：可以和修仙修魔随机事件绑在一起，功德负有概率堕落成魔修，影响随机事件好坏概率等等
功法法宝：增加修为功德等作用
钱庄系统：可以存储灵石等交易货币，可以设置储存上限以保证偷灵石和抢灵石功能不被影响

我个人的一些小想法，大佬们可以参考一下，希望这个插件可以越做越好

**Comment by s52047qwas** [comment]
钱庄系统预计增加，其他的做起来比较困难，可能后续会有
