### ISSUE TITLE
更新后提示路径失败，求解答一下

### ISSUE THREAD

**Issue by saferabbit** [s52047qwas/nonebot_plugin_xiuxian#69]
系统：Ubuntu20.04
nonebot2版本：2.0.0b5
Python版本： 3.9.14

那个load_all_plugins的路径具体是什么？我设置成bot的plugins还是提示找不到路径。
TypeError: the 'package' argument is required to perform a relative import

**Comment by saferabbit** [comment]
我尝试几种路径，已经可以

**Comment by saferabbit** [comment]
路径还是不生效，这个load_all_plugins模块是怎么设置的？

**Comment by s52047qwas** [comment]
当为放置为plugins目录使用时，请修改init处，load_all_plugins( [ 'nonebot_plugin_xiuxian.xiuxian_boss', ], 其中“nonebot_plugin_xiuxian.xiuxian_boss”修为为bot路径：例如： 'yuzi_bot.plugins.nonebot_plugin_xiuxian.xiuxian_boss'

**Comment by saferabbit** [comment]
虽然不是提示的那个，通过自己不断的尝试路径已经生效了
