### ISSUE TITLE
查看我的修仙信息和出关时发生错误

### ISSUE THREAD

**Issue by wuyukwi** [s52047qwas/nonebot_plugin_xiuxian#7]
![image](https://user-images.githubusercontent.com/86434647/188302537-6335c01d-b173-43cc-9c84-f028a3d13b67.png)

**Comment by s52047qwas** [comment]
你有调整数据库表字段吗？预计user_xiuxian表应该为12个字典，接收12个

**Comment by s52047qwas** [comment]
> ![image](https://user-images.githubusercontent.com/86434647/188302537-6335c01d-b173-43cc-9c84-f028a3d13b67.png)

你有调整数据库表字段吗？预计user_xiuxian表应该为12个字典，接收12个

**Comment by s52047qwas** [comment]
> ![image](https://user-images.githubusercontent.com/86434647/188302537-6335c01d-b173-43cc-9c84-f028a3d13b67.png)
发现数据库上传错了，你可以把库中的aa字段删除即可，或者重新拉去xiuxian.db文件
![image](https://user-images.githubusercontent.com/44226600/188308073-4c37128c-d1ea-4d1b-af16-976ec74f6b40.png)

**Comment by wuyukwi** [comment]
重新拉取了还是一样的报错

**Comment by wuyukwi** [comment]
解决了，谢谢
