### ISSUE TITLE
导入插件报错

### ISSUE THREAD

**Issue by xiayingLIULI** [s52047qwas/nonebot_plugin_xiuxian#71]
stdout: 10-20 11:50:38 [ERROR] nonebot | Failed to import "xiuxian_bank"
stdout: Traceback (most recent call last):
stdout:   File "/bot/bot.py", line 15, in <module>
stdout:     nonebot.load_plugins("extensive_plugin")
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
stdout:     return manager.load_all_plugins()
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
stdout:     return set(
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
stdout:     filter(None, (self.load_plugin(name) for name in self.available_plugins))
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
stdout:     module = importlib.import_module(
stdout:   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
stdout:     return _bootstrap._gcd_import(name[level:], package, level)
stdout:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
stdout:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
stdout:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
stdout:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
stdout:     super().exec_module(module)
stdout:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
stdout:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
stdout:   File "/bot/extensive_plugin/nonebot_plugin_xiuxian/__init__.py", line 75, in <module>
stdout:     nonebot.load_all_plugins(
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
stdout:     return manager.load_all_plugins()
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
stdout:     return set(
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
stdout:     filter(None, (self.load_plugin(name) for name in self.available_plugins))
stdout: > File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 143, in load_plugin
stdout:     module = importlib.import_module(self._third_party_plugin_names[name])
stdout:   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
stdout:     return _bootstrap._gcd_import(name[level:], package, level)
stdout:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
stdout:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
stdout:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
stdout:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
stdout:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
stdout:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
stdout:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
stdout:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
stdout:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
stdout:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
stdout:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
stdout:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
stdout:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
stdout:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
stdout:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
stdout:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
stdout:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
stdout:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
stdout:   File "/bot/bot.py", line 12, in <module>
stdout:     nonebot.load_plugin("nonebot_plugin_apscheduler")
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 32, in load_plugin
stdout:     manager = PluginManager([module_path])
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 52, in __init__
stdout:     self.prepare_plugins()
stdout:   File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 94, in prepare_plugins
stdout:     raise RuntimeError(
stdout: RuntimeError: Plugin already exists: nonebot_plugin_apscheduler! Check your plugin name

**Comment by s52047qwas** [comment]
1、参考readme处一些问题的说明设置对应的目录信息
2、也有可能是版本不一致导致。建议更新nonebot版本
