### ISSUE TITLE
【报错】当前的一些错误

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#77]
目前版本是当前时间最新版本 0.4.30
1、修仙帮助   指令无法打开，报错如下
![image](https://user-images.githubusercontent.com/70925546/197373600-e8628d84-b749-45ed-9f91-1e2400bbf81a.png)
2、boss生成   当之前boss到达上限后，重启无法生成世界boss并报boss数量已达上限（但重启已经删去boss）
![image](https://user-images.githubusercontent.com/70925546/197373824-10d8dc17-9616-45a7-bb25-770b17c9ac3d.png)

**Comment by Shinoakii** [comment]
1、data/xiuxian更新下资源文件
2、检查下xiuxian_boss下的config.json里有没有‘Boss个数上限’这个key

**Comment by Z735803792** [comment]
没有boss个数上限这个key，我尝试删除重启也没有

**Comment by Z735803792** [comment]
修仙帮助可以正常使用了

**Comment by Shinoakii** [comment]
没有这个key更新下xiuxian_boss文件夹下的bossconfig.py文件重启就会在json文件里生成

**Comment by Z735803792** [comment]
已正常使用，谢谢大佬
