### ISSUE TITLE
突破后攻击变低？

### ISSUE THREAD

**Issue by RShock** [s52047qwas/nonebot_plugin_xiuxian#78]
![B1WW
JL4$OY_Q{5 WF6)B](https://user-images.githubusercontent.com/11630758/197398222-aa729cb0-f4ba-4c7a-af04-b8e0d6e49c9f.jpg)

![)BD CVOLQNRYM`A@TWOJE56](https://user-images.githubusercontent.com/11630758/197398229-f8e2d753-2ddd-491e-8823-1637bf2438c8.jpg)

是否是正常的？

**Comment by Shinoakii** [comment]
正常，血蓝攻都是根据修为算的
