### ISSUE TITLE
缺少错误提示

### ISSUE THREAD

**Issue by wuyukwi** [s52047qwas/nonebot_plugin_xiuxian#8]
没有注册的情况也能改名和闭关，指令错误没有提示。比如没闭关的情况下出关没有提示

**Comment by s52047qwas** [comment]
> 没有注册的情况也能改名和闭关，指令错误没有提示。比如没闭关的情况下出关没有提示

已修复

**Comment by wuyukwi** [comment]
送灵石显示的是q号，能改成道号吗

**Comment by s52047qwas** [comment]
> 送灵石显示的是q号，能改成道号吗

如果是按照送灵石100道号，这种格式，就是显示道号
显示qq是因为本来是艾特对应用户，但是忘记写上去了

**Comment by wuyukwi** [comment]
刚发现的bug，排行榜获取不到筑基的人

**Comment by s52047qwas** [comment]
对应的sql为这一句，可以检查下xiuxian2_handle.py文件处的realm_top函数sql是否正确，最近有更新：
SELECT user_name,level,exp FROM user_xiuxian 
        WHERE user_name is NOT NULL
        ORDER BY CASE
        WHEN level = '元婴境圆满' THEN '10'
        WHEN level = '元婴境中期' THEN '11'
        WHEN level = '元婴境初期' THEN '12'
        WHEN level = '结丹境圆满' THEN '13'
        WHEN level = '结丹境中期' THEN '14'
        WHEN level = '结丹境初期' THEN '15'
        WHEN level = '筑基境圆满' THEN '16'
        WHEN level = '筑基境中期' THEN '17'
        WHEN level = '筑基境初期' THEN '18'
        WHEN level = '练气境圆满' THEN '19'
        WHEN level = '练气境中期' THEN '20'
        WHEN level = '练气境初期' THEN '21'
        WHEN level = '江湖好手' THEN '22'
        ELSE level END ASC,exp DESC

**Comment by wuyukwi** [comment]
我发现自动更新不会更新这个文件，需要手动替换吗

**Comment by s52047qwas** [comment]
因为pypi导入的包我还没有更新

**Comment by s52047qwas** [comment]
> 我发现自动更新不会更新这个文件，需要手动替换吗

优先更新github处代码，github处处理完成后，才会更新pypi

**Comment by s52047qwas** [comment]
> > 我发现自动更新不会更新这个文件，需要手动替换吗
> 
> 优先更新github处代码，github处处理完成后，才会更新pypi

pypi也同步更新了

**Comment by wuyukwi** [comment]
闭关达到上限后返回的是负数，是bug吗

**Comment by s52047qwas** [comment]
> 闭关达到上限后返回的是负数，是bug吗

预计是因为闭关设置了上限，当修为超过上限后，会变成负数，目前在调整上线，及根据灵根和境界增加修炼速度，后面应该不会出现这种情况了

**Comment by wuyukwi** [comment]
好的

**Comment by wuyukwi** [comment]
> > 闭关达到上限后返回的是负数，是bug吗
> 
> 预计是因为闭关设置了上限，当修为超过上限后，会变成负数，目前在调整上线，及根据灵根和境界增加修炼速度，后面应该不会出现这种情况了

要上线增加修炼速度了吗，那建议查看个人信息也把修炼速度加上去好点

**Comment by s52047qwas** [comment]
> > > 闭关达到上限后返回的是负数，是bug吗
> > 
> > 
> > 预计是因为闭关设置了上限，当修为超过上限后，会变成负数，目前在调整上线，及根据灵根和境界增加修炼速度，后面应该不会出现这种情况了
> 
> 要上线增加修炼速度了吗，那建议查看个人信息也把修炼速度加上去好点
修炼速度及个人信息处修炼速度都更新了

**Comment by wuyukwi** [comment]
> > > > 闭关达到上限后返回的是负数，是bug吗
> > > 
> > > 
> > > 预计是因为闭关设置了上限，当修为超过上限后，会变成负数，目前在调整上线，及根据灵根和境界增加修炼速度，后面应该不会出现这种情况了
> > 
> > 
> > 要上线增加修炼速度了吗，那建议查看个人信息也把修炼速度加上去好点
> > 修炼速度及个人信息处修炼速度都更新了

大佬好快的速度，pypi也更新了吗

**Comment by s52047qwas** [comment]
> > > > > 闭关达到上限后返回的是负数，是bug吗
> > > > 
> > > > 
> > > > 预计是因为闭关设置了上限，当修为超过上限后，会变成负数，目前在调整上线，及根据灵根和境界增加修炼速度，后面应该不会出现这种情况了
> > > 
> > > 
> > > 要上线增加修炼速度了吗，那建议查看个人信息也把修炼速度加上去好点
> > > 修炼速度及个人信息处修炼速度都更新了
> 
> 大佬好快的速度，个人信息显示的修仙速率的代码好像是因为转换int把小数舍弃了导致显示的百分比不对，负数的问题好像还是没有修复

是的。那里改的时候改错了，刚刚调好了，可以直接加个的qq沟通：578043031
