### ISSUE TITLE
【报错】描述和功能错误

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#80]
切磋时，如果对方血量为1 ，则提示 对方重伤藏匿了，无法抢劫！
希望可以切磋与血量没有关系

**Comment by Z735803792** [comment]
描述不准确，我意思是和当前血量没关系，就是双方以满血状态切磋？大概是这种。
同时报新的bug：宗门功法/者神通学习后，再次输入学习指令，报的却是宗门无此功法/神通

**Comment by Shinoakii** [comment]
我这没这问题，可能代码不是最新的

**Comment by Z735803792** [comment]
谢谢大佬问题已修复
