### ISSUE TITLE
同时抢boss出现鞭尸以及抢人头问题

### ISSUE THREAD

**Issue by RShock** [s52047qwas/nonebot_plugin_xiuxian#85]
聊天记录
==========

【吐槽】群欧皇，吸光群友欧气 2022/10/28 15:00:01
讨伐boss3

--------------
【活跃】花千树 2022/10/28 15:00:01
讨伐boss3

--------------
【管理员】里真寻 2022/10/28 15:00:02
[群聊的聊天记录]

          【管理员】Boss战 14:55:01
          ☆------群土豪，全是面包的回合------☆
          
          【管理员】Boss战 14:55:01
          群土豪，全是面包发起攻击，造成了22978伤害
          
          【管理员】Boss战 14:55:01
          洪荒蛮龙剩余血量-43133
          
          【管理员】Boss战 14:55:01
          群土豪，全是面包胜利

--------------
【管理员】里真寻 2022/10/28 15:00:02
[群聊的聊天记录]

          【管理员】Boss战 14:55:01
          ☆------黄叶树的回合------☆
          
          【管理员】Boss战 14:55:01
          黄叶树发起攻击，造成了22285伤害
          
          【管理员】Boss战 14:55:01
          洪荒蛮龙剩余血量529805
          
          【管理员】Boss战 14:55:01
          ☆------洪荒蛮龙的回合------☆
          
          【管理员】Boss战 14:55:01
          洪荒蛮龙发起会心一击，造成了5409伤害
          
          【管理员】Boss战 14:55:01
          黄叶树剩余血量104916
          （下略）

--------------
【管理员】里真寻 2022/10/28 15:00:02
恭喜道友击败洪荒蛮龙，收获灵石20000枚（给了第一个鞭尸的人）

--------------

希望在战斗前加一个血量判断（或者异步锁什么的）防止抢人头行为

**Comment by Z735803792** [comment]
加个合刀吧）

**Comment by Shinoakii** [comment]
Boss战加了个锁
