### ISSUE TITLE
【严重问题】每日定时刷新签到，任务无效

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#91]
连续两天，`修仙签到`和宗门任务什么的都没有刷新了，这两天正好从0.4.30更新到0.4.31版本
由于0点直接睡大觉，并没有看到报错
ubuntu20.04
python3.9.15
nonebot2=2.0.0b5
nonebot_plugin_apscheduler==0.1.4

**Comment by Shinoakii** [comment]
我这没问题，大概你的nonebot_plugin_apscheduler有问题试一下更新这个插件
