### ISSUE TITLE
【报错】讨伐世界boss失败

### ISSUE THREAD

**Issue by Z735803792** [s52047qwas/nonebot_plugin_xiuxian#93]
已更新最新版本
`讨伐世界boss1`
bot端无回复
![image](https://user-images.githubusercontent.com/70925546/200117196-7dfb5e52-eed6-4677-b9b6-a55cbf4065cf.png)

**Comment by Z735803792** [comment]
出关报错
![image](https://user-images.githubusercontent.com/70925546/200117374-18222228-6065-48ca-bec3-bd57dcfbe2a8.png)
突破报错
![image](https://user-images.githubusercontent.com/70925546/200117390-61fbc659-96e6-431d-95e1-67344aacc5ec.png)

**Comment by Shinoakii** [comment]
1、git上的player_fight.py里这个方法是return hpcost, mpcost, secbuffdata['skill_type'], secbuffdata['rate']，你看看有没有更新吧

**Comment by Shinoakii** [comment]
2、出关、突破报错检查下json文件吧，我这没这问题

**Comment by Z735803792** [comment]
谢谢大佬，1是因为用的镜像源更新版本低了已经修复。
2是我想自己加几个境界结果格式错了
