### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by yinanwang385** [s52047qwas/nonebot_plugin_xiuxian#94]
谢谢修仙插件，群友很喜欢。
顺便想问一下，每次更新只需要用”pip install nonebot-plugin-xiuxian -U或者pip install nonebot-plugin-xiuxian --upgrade“这两个代码就可以了么？
我使用后并没有更新呀？

**Comment by Shinoakii** [comment]
pip稳定后更新，最新代码要下载git源码（不稳定，随机奖励点bug）
